### DISCUSSION TITLE
Not able to get the live view work, only be able to see the annotations

### DISCUSSION THREAD

**Discussion by lnshi** [actions-rs/meta#45] [Q&A]
hi, firstly thanks a lot for this awesome actions, the live view indeed make the review work a lot easier, but i followed the sample flow cannot get the live view work on the code, only be able to see the annotations were created, what i could be missing?

```
jobs:
  linting:
    name: Static code linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/checkout@v2

      - name: Install clippy
        run: rustup component add clippy

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          args: >
            --manifest-path=rsmain/Cargo.toml
            --
            --deny=warnings
            --allow=clippy::module_inception
            --allow=clippy::new_ret_no_self
```

BTW, i am using it against a private repo, is that the issue or private repo requires some special settings?
