### ISSUE TITLE
[question] How to use different features on different toolchains?

### ISSUE THREAD

**Issue by WaffleLapkin** [actions-rs/meta#18]
I was trying to setup CI using gt actions (for the start I copy-pasted [`matrix`] example) and ran into a problem.

For my `nightly` and `stable` build I need different cargo-features (like `--features "a"` and `--features "stable a"`) for all commands (`build`, `test`, `fmt`, `clippy`).

How can I do that? Maybe it's possible to change env depending on toolchain and then use paste env into commands?

[`matrix`]: https://github.com/actions-rs/meta/blob/master/recipes/matrix.md

**Comment by svartalf** [comment]
From my understanding, the only reasonable option for now is to use two different steps with [`if` directive](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#jobsjob_idstepsif), sort of:

```yaml
steps:
  - name: stable build 
    uses: actions-rs/cargo@v1
    if: matrix.rust == 'stable'
    with:
      args: --features "stable a" 
  - name: nightl build 
    uses: actions-rs/cargo@v1
    if: matrix.rust == 'nightly'
    with:
      args: --features "a" 
```

Also, consider using the [GitHub community forum](https://github.community/), please, as this question seems to be unrelated to the **Rust** Actions, but mostly related to Actions workflow syntax in a whole.
