### ISSUE TITLE
Caching tracking issue

### ISSUE THREAD

**Issue by svartalf** [actions-rs/meta#21]
There are two things that can be improved with caching added:

1. Cache `target/` and Cargo folders (see [an example](https://github.com/actions/cache/blob/master/examples.md#rust---cargo))
2. Cache the compiled binary from the `cargo install {pkgid}` command

Right now this affects the following workflows:

 * `actions-rs/cargo` with `use-cross: true` input enabled (`cross` is compiled on each call)
 * https://github.com/actions-rs/tarpaulin/pull/1
 * https://github.com/actions-rs/meta/issues/20
 * https://github.com/actions-rs/meta/issues/13
 * https://github.com/actions-rs/meta/issues/11
 * https://github.com/actions-rs/meta/issues/5

This issue can be solved by a proper implementation of the `actions-rs/core/Cargo.installCached` function, see https://github.com/actions-rs/core/issues/31, but it is blocked by https://github.com/actions/cache/issues/55

Right now this issue acts only as a tracking issue for a possibility of proper caching implementation.

**Comment by jhpratt** [comment]
For anyone looking for an example of how cacheing can be done currently, checkout the [time-rs/time](https://github.com/time-rs/time) repo. I just enabled cacheing of both the target and toolchain directories for my entire matrix. It shaved about a minute off of my overall time in my first test.

**Comment by CAD97** [comment]
[In rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/blob/ce5684216eda52a6da6a2933a980bd5655da61b8/.github/workflows/ci.yaml#L85-L90), we remove artifacts for the workspace-local files before the cache stores. While this isn't required to reduce cache churn like it does on auto-keyed caching (e.g. Travis) (as a matching key will not store the cache), it does still reduce cache sizes.

If actions-rs ever provides a "best practice" caching wrapper, it should probably allow scrubbing these files, so only dependencies' artifacts are cached. (Specifically, scrubbing files directly in `./target/{debug,release}/` as well as folders/files directly in `./target/{debug,release/{.fingerprint,deps,incremental}/` that contain the names of workspace-local libs/bins.

**Comment by svartalf** [comment]
@CAD97 noted, thank you! I do want to create some kind of `actions-rs/cache`, which will cache all these things automatically, but as this issue points to, there is no programmatic access to the cache routines right now.

**Comment by anp** [comment]
Lucky timing, but looks like a few hours before I came across this issue someone posted a possible workaround to the upstream issue: https://github.com/actions/cache/issues/55#issuecomment-612575988.

Also worth noting that in addition to the target/ directory examples, currently I have these cache keys set up in my jobs:

```yaml
    - name: cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: cargo-index-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-index-
    - name: cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: cargo-registry-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-registry-
```
