### ISSUE TITLE
Support `working-directory`

### ISSUE THREAD

**Issue by asomers-ax** [actions-rs/meta#28]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [ ] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

Other github actions support a `working-directory` attribute that changes the directory before running any command.  `actions-rs` should do that too.  For example, trying to do `cargo build --feature=XXX` in a workspace won't work; the `--feature=` switch doesn't work in workspaces.  Instead, you must cd into an individual crate to build it with specified features.

## Workflow example

```yaml
    - name: test-with-XXX
      uses: actions-rs/cargo@v1
      working-directory: my_subcrate
      with:
        command: test
        args: --features=XXX
```
