### ISSUE TITLE
How to handle multiple crates scattered throughout my repo?

### ISSUE THREAD

**Issue by mnp** [actions-rs/meta#30]
Do the checklist before filing an issue:

 * [x] Is this related to the `actions-rs` Actions?
       If you think it's a problem related to Github Actions in general, use GitHub Community forum instead: https://github.community
 * [x] You've read the Contributing section about feature requests: https://github.com/actions-rs/.github/blob/master/CONTRIBUTING.md#feature-requests
 * [ ] Is this something you can debug and fix? Send a pull request! Bug fixes and documentation fixes are welcome.

## Motivation

I have a monorepo with various languages, rust included, at different levels. I don't see how the actions should be used in this case.  My brute force approach is to define a Makefile target that recurses my repo like this, 
```Makefile
SUBDIRS = $(dir $(shell find . -name Cargo.toml))
test-rust:
        for dir in $(SUBDIRS); do ( cd $$dir && cargo test --verbose); done
```
... and then call `make test-rust` from the GH action, after setting up the environment.  This seems hacky.

## Workflow example
/shrug -- I'm thinking there should be a --recursive-find-crate sort of option.

## Additional context
There are existing discussions around pointing to one particular workspace or crate: #27 and #28 which seem germane but don't solve my problem.

Any advise?

**Comment by lskatz** [comment]
I checked out my repo to a new path and I cannot figure out how to change the path for `cargo build` either

```
      - uses: actions/checkout@v3
        with:
          path: fasten
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features 
```
